repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.10.0
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.15.0"
      hooks:
          - id: mypy
            args: [--strict]

    - repo: https://github.com/pycqa/isort
      rev: 5.11.2
      hooks:
        - id: isort
          name: isort (python)

    - repo: https://github.com/fpgmaas/deptry.git
      rev: 0.23.0
      hooks:
        - id: deptry
          args: ["--ignore", "DEP001"]